forum_root/app_users/urls.py
from django.urls import path
from .views import UserLoginView, UserLogoutView, UserRegistrationView, profile, update_profile


urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/', profile, name='profile'),
    path('edit/', update_profile, name='update_profile')
]

forum_root/forum/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('main.urls')),
    path('accounts/', include('app_users.urls')),
    path('archive/', include('archive.urls'))
] + static (settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

forum_root/main/urls.py
from django.urls import path
from .views import  create_thread, index, ThreadListView, thread_view


urlpatterns = [
    path('', index, name='index'),
    path('sections/<int:pk>', ThreadListView.as_view(), name='section'),
    path('thread/<int:pk>', thread_view, name='thread'),
    path('create_thread/<int:pk>', create_thread, name='create_th'),
    # path('edit_post/<int:pk>', UpdatePostView.as_view(), name='edit_post')
    
]

forum_root/app_users/models.py
from cgitb import text
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class AdvUser(AbstractUser):
    date_of_birth = models.DateField(null=True, verbose_name='Дата рождения', help_text='Дата рождения через "/"')
    avatar = models.ImageField(upload_to='user/', null=True, blank=True)
    info = models.TextField(null=True)
    
    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

forum_root/main/models.py
from tabnanny import verbose
from ckeditor.fields import RichTextField

from django.db import models

from app_users.models import AdvUser

class Section(models.Model):
    section_name = models.CharField(max_length=30, unique=True, verbose_name='Раздел')
    
    def __str__(self) -> str:
        return self.section_name
    
    class Meta:
        verbose_name = 'Раздел'
        verbose_name_plural = 'Разделы'
    
class Thread(models.Model):
    thread_name = models.CharField(max_length=100, verbose_name='Тема')
    section_id = models.ForeignKey(Section, on_delete=models.CASCADE, verbose_name='Раздел')
    is_open = models.BooleanField(verbose_name='Открыто ли обсуждение?', default=True)   
    
    def __str__(self) -> str:
        return self.thread_name
    
    
    class Meta:
        verbose_name = 'Тему'
        verbose_name_plural = 'Темы'
    
    
class Post(models.Model):
    tread_id = models.ForeignKey(Thread, null=True, on_delete=models.CASCADE, related_name='posts', verbose_name='Тема')
    user_id = models.ForeignKey(AdvUser, null=False, on_delete=models.CASCADE, related_name='posts', verbose_name='Пользователь')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Изменено')
    text = RichTextField(max_length=1000, verbose_name='Текст сообщения')
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    
    def show_post(self):
        return self.text[0:100] + '...'
        
    
    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
    
    def __str__(self) -> str:
        return self.text[:10] + '...'
    
    

    

forum_root/app_users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import AdvUser


class AuthForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
    
class RegistrationForm(UserCreationForm):
    class Meta:
        model = AdvUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'avatar')
        
class UpdateProfileForm(forms.Form):
    info = forms.CharField(label='Расскажите о себе',
                   widget=forms.Textarea(attrs={'class': 'ckeditor'}))
    class Meta:
        model = AdvUser
        fields = ('info',)

forum_root/app_users/views.py
from multiprocessing import context
from django.shortcuts import redirect, render
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required


from main.utils import DataMixin

from .models import AdvUser
from .forms import AuthForm, RegistrationForm, UpdateProfileForm

# Create your views here.
class UserRegistrationView(DataMixin, CreateView):
    model = AdvUser
    form_class = RegistrationForm
    template_name = 'register.html'
    success_url = reverse_lazy('login')
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['sections'] = self.sections
        return context
    
class UserLoginView(DataMixin, LoginView):
    template_name = 'login.html'
    next_page = reverse_lazy('profile')
    form = AuthForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sections'] = self.sections
        return context
    
class UserLogoutView(LogoutView):
    next_page = '/'
    
@login_required    
def profile(request):
    return render(request, 'profile.html', {'sections' : DataMixin.sections})


def update_profile(request):
    if request.method == 'POST':
        form = UpdateProfileForm(request.POST)
        if form.is_valid():
            user = AdvUser.objects.get(pk=request.user.pk)
            user.info = form.cleaned_data['info']
            user.save()
            return redirect(reverse_lazy('profile'))
    else:
        form = UpdateProfileForm()
        context = {
            'form' : form,
            'sections' : DataMixin.sections
        }
        return render(request, 'update_profile.html', context=context)
            

forum_root/app_users/templates/by_section.html
{% extends 'layout/base.html' %}

{% block content %}
<h2>{{section.section_name}}</h2>
<a href="{% url 'create_th' section.pk %}"><button class="pressed-button">Создать обсуждение</button></a>
<ul>
{% for thread in thread_list %}

    <a href="{% url 'thread' thread.pk %}"><li>{{ thread.thread_name }}</li></a>

{% endfor %}
</ul>
{% endblock %}

forum_root/app_users/templates/create_thread.html
{% extends 'layout/base.html' %}


{% block content %}

<form  action="" method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Создать</button>
</form>

{% endblock %}

forum_root/app_users/templates/index.html
{% extends 'layout/base.html' %}



{% block content %}
    {% for sec, thread in secthread.items %}
    <div class="thread-list">
        <h2><a href="{% url 'section' sec.pk %}">{{sec.section_name}}</a></h2>
        
            <ul>
                {% for t in thread %}
                <a href="{% url 'thread' t.pk %}"><li>{{ t.thread_name }}</li></a>
                {% endfor %}
            </ul>
    </div>
        {% endfor %}       
    
{% endblock %}

forum_root/app_users/templates/login.html
{% extends 'layout/base.html' %}

{% block title %} Вход {% endblock %}

{% block content %}
<form class="registration-form" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="pressed-button" type="submit">Войти</button>
</form>

{% endblock %}

forum_root/app_users/templates/post_edit.html
{% extends 'layout/base.html' %}

{% block content %}

{{ form.as_p }}

{% endblock %}

forum_root/app_users/templates/profile.html
{% extends 'layout/base.html' %}
{% load static %}
{% block content %}

<div class="profile">
    {% if user.avatar %}
    <img src="{{user.avatar.url}}">
    {% else %}
    <img src="{% static 'img/noava.png' %}" alt="">
    {% endif %}
    <p>Ваш логин: {{ user.username }}</p>
    <p> {{ user.first_name }}</p>
    <p>Имя: {{user.last_name}}</p>
    <p>Ваш e-mail: {{user.email}}</p>
    <p>Дата регистрации: {{user.date_joined}}</p>
    {% if user.info %}
    <p>Расскажите о себе: {{user.info | safe}}</p>
    {% else %}
    <p>Расскажите о себе:</p>
    {% endif %}
    
    <button class="pressed-button"><a href="{% url 'update_profile' %}">Изменить информацию</a></button>
</div> 

{% endblock %}

forum_root/app_users/templates/register.html
{% extends 'layout/base.html' %}

{% block title %} Регистрация {% endblock %}

{% block content %}
<form class="registration-form" action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button class="pressed-button"  type="submit">Зарегистрироваться</button>
</form>

{% endblock %}

forum_root/app_users/templates/thread.html
{% extends 'layout/base.html' %}


{% block content %}
<ul>
    {% for post in posts %}
    <li>{{ post.text | safe }}</li>
    {% endfor %}
</ul>

<hr>
{% if user.is_authenticated %}
<div class="create-post">
    <h3>Введите сообщение</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.post_text }}
        <button class="pressed-button" type="submit">Отправить</button>
    </form>
</div>
{% else %}
<h2>Отправлять сообщения могут только зарегистрированные пользователи, <a href="{% url 'index' %}">Войти</a></h2>
{% endif %}
{% endblock %}

forum_root/app_users/templates/update_profile.html
{% extends 'layout/base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="pressed-button">Обновить</button>
</form>

{% endblock %}